import { getPages } from "@/sanity/sanity-utils";
import "../globals.css";
import Link from "next/link";
import { RippleBackground } from "./animations/RippleBackground";
import HomeLink from "./animations/HomePageSpin";

export const metadata = {
  title: "Grant",
  description: "Generated by Next + Sanity + Tailwind CSS",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // get all of our pages
  const pages = await getPages();

  return (
    <html lang="en">
      <body className="bg-minimalist max-w mx-auto py-10">
        <RippleBackground />
        <header className="flex justify-between items-center px-4 sm:px-6 lg:px-8">
          <HomeLink />

          <div className="flex items-center gap-5 text-md text-gray-400">
            {pages.map((page) => (
              <Link
                key={page._id}
                href={`/${page.slug}`}
                className="text-transparent bg-clip-text bg-gradient-to-r from-gray-200 to-gray-200 hover:from-pink-500 hover:to-orange-500 transition-all ease-in-out transform hover:scale-110"
              >
                {page.title}
              </Link>
            ))}
          </div>
        </header>
        <main className="py-20 px-4 sm:px-6 lg:px-8 text-center">
          {children}
        </main>
      </body>
    </html>
  );
}
