import { getPages } from "@/sanity/sanity-utils";
import "../globals.css";
import Link from "next/link";

export const metadata = {
  title: "My Awesome Site",
  description: "Generated by Next + Sanity + Tailwind CSS",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // get all of our pages
  const pages = await getPages();

  return (
    <html lang="en">
      <body className="bg-minimalist max-w mx-auto py-10">
        <header className="flex justify-between items-center px-4 sm:px-6 lg:px-8">
          <Link
            href="/"
            className="bg-gradient-to-r via-red-500 from-orange-400 to-purple-600 bg-clip-text text-transparent text-lg font-bold"
          >
            Grant
          </Link>

          <div className="flex items-center gap-5 text-sm text-gray-600">
            {pages.map((page) => (
              <Link
                key={page._id}
                href={`/${page.slug}`}
                className="hover:underline"
              >
                {page.title}
              </Link>
            ))}
          </div>
        </header>
        <main className="py-20 px-4 sm:px-6 lg:px-8 text-center">
          {children}
        </main>
      </body>
    </html>
  );
}
